-- silver.nfhs5_district: cleaned NFHS-5 district indicators.
-- Rules (AGENTS.md gotcha #2): '*' (suppressed) -> NULL, never 0; parenthesised
-- small-sample values kept but counted in nfhs_small_sample_cols (low-confidence);
-- all numeric-bearing string columns try_cast to DOUBLE. Adds normalized join keys.
-- GENERATED from information_schema (49 numeric-string cols cleaned).
CREATE OR REPLACE TABLE mdp.silver.nfhs5_district AS
SELECT
  `district_name`,
  `state_ut`,
  trim(regexp_replace(upper(trim(`district_name`)), '[^A-Z0-9]+', ' ')) AS norm_district,
  trim(regexp_replace(upper(trim(`state_ut`)),      '[^A-Z0-9]+', ' ')) AS norm_state,
  (CASE WHEN trim(`sex_ratio_at_birth_5y_f_per_1000_m`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`deaths_in_the_last_3_years_civil_reg_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`child_5y_who_attended_pre_primary_school_during_the_school_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`w20_24_married_before_age_18_years_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`births_in_the_5_years_preceding_the_survey_that_are_birth_3_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`w15_19_who_were_already_mothers_or_pregnant_at_the_time_of_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`current_users_ever_told_about_side_effects_of_current_metho_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`mothers_who_had_an_anc_visit_in_the_first_trimester_lb5y_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`mothers_who_had_at_least_4_anc_visits_lb5y_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`mothers_whose_last_birth_was_protected_against_neo_tetanus_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`mothers_who_consumed_ifa_for_100_days_or_more_when_they_wer_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`mothers_who_consumed_ifa_for_180_days_or_more_when_they_wer_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`registered_pregnancies_for_which_the_mother_received_a_mcp_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`mothers_who_received_pnc_from_a_doctor_nurse_lhv_anm_midwif_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`average_out_of_pocket_expenditure_per_delivery_in_a_public_fac`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`children_born_at_home_who_were_taken_to_a_health_facility_f_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`children_who_received_pnc_from_a_doctor_nurse_lhv_anm_midwi_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`births_in_a_private_fac_that_were_delivered_by_csection_5y_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`births_in_a_public_fac_that_were_delivered_by_csection_5y_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`child_12_23m_fully_vaccinated_based_on_information_from_eit_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`child_12_23m_fully_vaccinated_based_on_information_from_vax_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`child_12_23m_who_have_received_bcg_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`child_12_23m_who_have_received_3_doses_of_polio_vaccine_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`child_12_23m_who_have_received_3_doses_of_penta_or_dpt_vacc_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`child_12_23m_who_have_received_the_first_dose_of_mcv_mcv_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`child_24_35m_who_have_received_a_second_dose_of_mcv_mcv_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`child_12_23m_who_have_received_3_doses_of_rotavirus_vaccine_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`child_12_23m_who_have_received_3_doses_of_penta_or_hepatiti_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`child_9_35m_who_received_a_vit_a_in_the_last_6_months_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`child_12_23m_who_received_most_of_their_vaccinations_in_a_p_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`child_12_23m_who_received_most_of_their_vaccinations_in_a_2_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`children_with_diarrhoea_2wk_who_received_oral_rehydration_s_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`children_with_diarrhoea_2wk_who_received_zinc_child_u5_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`children_with_diarrhoea_2wk_taken_to_a_health_facility_or_h_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`children_with_fever_or_symptoms_of_ari_2wk_taken_to_a_healt_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`children_under_age_3_years_breastfed_within_one_hour_of_bir_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`child_u6m_exclusively_breastfed_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`child_6_8m_receiving_solid_or_semi_solid_food_and_breastmil_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`breastfeeding_child_6_23m_receiving_an_adequate_diet16_17_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`non_breastfeeding_child_6_23m_receiving_an_adequate_diet16_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`total_child_6_23m_receiving_an_adequate_diet16_17_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`child_u5_who_are_stunted_height_for_age_18_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`child_u5_who_are_wasted_weight_for_height_18_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`child_u5_who_are_severe_wasted_weight_for_height_19_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`child_u5_who_are_underweight_weight_for_age_18_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`child_u5_who_are_overweight_weight_for_height_20_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`child_6_59m_who_are_anaemic_lt_11_0_g_dl_22_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`pregnant_w15_49_who_are_anaemic_lt_11_0_g_dl_22_pct`) LIKE '(%)' THEN 1 ELSE 0 END + CASE WHEN trim(`all_w15_19_who_are_anaemic_pct`) LIKE '(%)' THEN 1 ELSE 0 END) AS nfhs_small_sample_cols,
  `households_surveyed`,
  `women_15_49_interviewed`,
  `men_15_54_interviewed`,
  `female_population_age_6_years_and_above_ever_schooled_pct`,
  `population_below_age_15_years_pct`,
  `sex_ratio_total_f_per_1000_m`,
  `child_u5_whose_birth_was_civil_reg_pct`,
  `hh_electricity_pct`,
  `hh_improved_water_pct`,
  `hh_use_improved_sanitation_pct`,
  `households_using_clean_fuel_for_cooking_pct`,
  `households_using_iodized_salt_pct`,
  `hh_member_covered_health_insurance_pct`,
  `women_age_15_49_who_are_literate_pct`,
  `women_age_15_49_with_10_or_more_years_of_schooling_pct`,
  `w15_24_who_use_menstrual_hygiene_pct`,
  `fp_cm_w15_49_any_method_pct`,
  `fp_cm_w15_49_modern_method_pct`,
  `fp_cm_w15_49_f_steril_pct`,
  `fp_cm_w15_49_m_steril_pct`,
  `fp_cm_w15_49_iud_pct`,
  `fp_cm_w15_49_pill_pct`,
  `fp_cm_w15_49_condom_pct`,
  `fp_cm_w15_49_injectables_pct`,
  `fp_unmet_total_cm_w15_49_7_pct`,
  `fp_unmet_spacing_cm_w15_49_7_pct`,
  `health_worker_ever_talked_to_female_non_users_about_family_pct`,
  `institutional_birth_5y_pct`,
  `institutional_birth_in_public_facility_5y_pct`,
  `home_birth_that_were_conducted_by_skilled_hp_5y_10_pct`,
  `births_attended_by_skilled_hp_5y_10_pct`,
  `births_delivered_by_csection_5y_pct`,
  `prev_diarrhoea_2wk_child_u5_pct`,
  `children_prev_symptoms_of_acute_respiratory_infection_ari_2_pct`,
  `women_age_15_49_years_whose_bmi_bmi_is_underweight_bmi_lt_1_pct`,
  `women_age_15_49_years_who_are_overweight_obese_bmi_gte_25_0_pct`,
  `women_age_15_49_years_who_have_high_risk_whr_gte_0_85_pct`,
  `non_pregnant_w15_49_who_are_anaemic_lt_12_0_g_dl_22_pct`,
  `all_w15_49_who_are_anaemic_pct`,
  `women_age_15_years_and_above_with_high_141_160_mg_dl_blood_pct`,
  `w15_plus_with_very_high_gt_160_mg_dl_blood_sugar_pct`,
  `w15_plus_with_high_or_very_high_gt_140_mg_dl_blood_sugar_or_pct`,
  `m15_plus_with_high_141_160_mg_dl_blood_sugar_pct`,
  `men_age_15_years_and_above_with_very_high_gt_160_mg_dl_bloo_pct`,
  `m15_plus_with_high_or_very_high_gt_140_mg_dl_blood_sugar_or_pct`,
  `w15_plus_with_mildly_high_bp_sys_140_159_mmhg_and_or_dia_90_pct`,
  `w15_plus_with_moderately_or_severely_high_bp_sys_gte_160_mm_pct`,
  `w15_plus_with_high_bp_sys_gte_140_mmhg_and_or_dia_gte_90_mm_pct`,
  `m15_plus_with_mildly_high_bp_sys_140_159_mmhg_and_or_dia_90_pct`,
  `m15_plus_with_moderately_or_severely_high_bp_sys_gte_160_mm_pct`,
  `m15_plus_with_high_bp_sys_gte_140_mmhg_and_or_dia_gte_90_mm_pct`,
  `women_age_30_49_years_ever_undergone_a_cervical_screen_pct`,
  `women_age_30_49_years_ever_undergone_a_breast_exam_pct`,
  `women_age_30_49_years_ever_undergone_an_oral_cancer_exam_pct`,
  `w15_plus_who_use_any_kind_of_tobacco_pct`,
  `m15_plus_who_use_any_kind_of_tobacco_pct`,
  `w15_plus_who_consume_alcohol_pct`,
  `m15_plus_who_consume_alcohol_pct`,
  try_cast(regexp_replace(nullif(trim(`sex_ratio_at_birth_5y_f_per_1000_m`), '*'), '[()]', '') AS DOUBLE) AS `sex_ratio_at_birth_5y_f_per_1000_m`,
  try_cast(regexp_replace(nullif(trim(`deaths_in_the_last_3_years_civil_reg_pct`), '*'), '[()]', '') AS DOUBLE) AS `deaths_in_the_last_3_years_civil_reg_pct`,
  try_cast(regexp_replace(nullif(trim(`child_5y_who_attended_pre_primary_school_during_the_school_pct`), '*'), '[()]', '') AS DOUBLE) AS `child_5y_who_attended_pre_primary_school_during_the_school_pct`,
  try_cast(regexp_replace(nullif(trim(`w20_24_married_before_age_18_years_pct`), '*'), '[()]', '') AS DOUBLE) AS `w20_24_married_before_age_18_years_pct`,
  try_cast(regexp_replace(nullif(trim(`births_in_the_5_years_preceding_the_survey_that_are_birth_3_pct`), '*'), '[()]', '') AS DOUBLE) AS `births_in_the_5_years_preceding_the_survey_that_are_birth_3_pct`,
  try_cast(regexp_replace(nullif(trim(`w15_19_who_were_already_mothers_or_pregnant_at_the_time_of_pct`), '*'), '[()]', '') AS DOUBLE) AS `w15_19_who_were_already_mothers_or_pregnant_at_the_time_of_pct`,
  try_cast(regexp_replace(nullif(trim(`current_users_ever_told_about_side_effects_of_current_metho_pct`), '*'), '[()]', '') AS DOUBLE) AS `current_users_ever_told_about_side_effects_of_current_metho_pct`,
  try_cast(regexp_replace(nullif(trim(`mothers_who_had_an_anc_visit_in_the_first_trimester_lb5y_pct`), '*'), '[()]', '') AS DOUBLE) AS `mothers_who_had_an_anc_visit_in_the_first_trimester_lb5y_pct`,
  try_cast(regexp_replace(nullif(trim(`mothers_who_had_at_least_4_anc_visits_lb5y_pct`), '*'), '[()]', '') AS DOUBLE) AS `mothers_who_had_at_least_4_anc_visits_lb5y_pct`,
  try_cast(regexp_replace(nullif(trim(`mothers_whose_last_birth_was_protected_against_neo_tetanus_pct`), '*'), '[()]', '') AS DOUBLE) AS `mothers_whose_last_birth_was_protected_against_neo_tetanus_pct`,
  try_cast(regexp_replace(nullif(trim(`mothers_who_consumed_ifa_for_100_days_or_more_when_they_wer_pct`), '*'), '[()]', '') AS DOUBLE) AS `mothers_who_consumed_ifa_for_100_days_or_more_when_they_wer_pct`,
  try_cast(regexp_replace(nullif(trim(`mothers_who_consumed_ifa_for_180_days_or_more_when_they_wer_pct`), '*'), '[()]', '') AS DOUBLE) AS `mothers_who_consumed_ifa_for_180_days_or_more_when_they_wer_pct`,
  try_cast(regexp_replace(nullif(trim(`registered_pregnancies_for_which_the_mother_received_a_mcp_pct`), '*'), '[()]', '') AS DOUBLE) AS `registered_pregnancies_for_which_the_mother_received_a_mcp_pct`,
  try_cast(regexp_replace(nullif(trim(`mothers_who_received_pnc_from_a_doctor_nurse_lhv_anm_midwif_pct`), '*'), '[()]', '') AS DOUBLE) AS `mothers_who_received_pnc_from_a_doctor_nurse_lhv_anm_midwif_pct`,
  try_cast(regexp_replace(nullif(trim(`average_out_of_pocket_expenditure_per_delivery_in_a_public_fac`), '*'), '[()]', '') AS DOUBLE) AS `average_out_of_pocket_expenditure_per_delivery_in_a_public_fac`,
  try_cast(regexp_replace(nullif(trim(`children_born_at_home_who_were_taken_to_a_health_facility_f_pct`), '*'), '[()]', '') AS DOUBLE) AS `children_born_at_home_who_were_taken_to_a_health_facility_f_pct`,
  try_cast(regexp_replace(nullif(trim(`children_who_received_pnc_from_a_doctor_nurse_lhv_anm_midwi_pct`), '*'), '[()]', '') AS DOUBLE) AS `children_who_received_pnc_from_a_doctor_nurse_lhv_anm_midwi_pct`,
  try_cast(regexp_replace(nullif(trim(`births_in_a_private_fac_that_were_delivered_by_csection_5y_pct`), '*'), '[()]', '') AS DOUBLE) AS `births_in_a_private_fac_that_were_delivered_by_csection_5y_pct`,
  try_cast(regexp_replace(nullif(trim(`births_in_a_public_fac_that_were_delivered_by_csection_5y_pct`), '*'), '[()]', '') AS DOUBLE) AS `births_in_a_public_fac_that_were_delivered_by_csection_5y_pct`,
  try_cast(regexp_replace(nullif(trim(`child_12_23m_fully_vaccinated_based_on_information_from_eit_pct`), '*'), '[()]', '') AS DOUBLE) AS `child_12_23m_fully_vaccinated_based_on_information_from_eit_pct`,
  try_cast(regexp_replace(nullif(trim(`child_12_23m_fully_vaccinated_based_on_information_from_vax_pct`), '*'), '[()]', '') AS DOUBLE) AS `child_12_23m_fully_vaccinated_based_on_information_from_vax_pct`,
  try_cast(regexp_replace(nullif(trim(`child_12_23m_who_have_received_bcg_pct`), '*'), '[()]', '') AS DOUBLE) AS `child_12_23m_who_have_received_bcg_pct`,
  try_cast(regexp_replace(nullif(trim(`child_12_23m_who_have_received_3_doses_of_polio_vaccine_pct`), '*'), '[()]', '') AS DOUBLE) AS `child_12_23m_who_have_received_3_doses_of_polio_vaccine_pct`,
  try_cast(regexp_replace(nullif(trim(`child_12_23m_who_have_received_3_doses_of_penta_or_dpt_vacc_pct`), '*'), '[()]', '') AS DOUBLE) AS `child_12_23m_who_have_received_3_doses_of_penta_or_dpt_vacc_pct`,
  try_cast(regexp_replace(nullif(trim(`child_12_23m_who_have_received_the_first_dose_of_mcv_mcv_pct`), '*'), '[()]', '') AS DOUBLE) AS `child_12_23m_who_have_received_the_first_dose_of_mcv_mcv_pct`,
  try_cast(regexp_replace(nullif(trim(`child_24_35m_who_have_received_a_second_dose_of_mcv_mcv_pct`), '*'), '[()]', '') AS DOUBLE) AS `child_24_35m_who_have_received_a_second_dose_of_mcv_mcv_pct`,
  try_cast(regexp_replace(nullif(trim(`child_12_23m_who_have_received_3_doses_of_rotavirus_vaccine_pct`), '*'), '[()]', '') AS DOUBLE) AS `child_12_23m_who_have_received_3_doses_of_rotavirus_vaccine_pct`,
  try_cast(regexp_replace(nullif(trim(`child_12_23m_who_have_received_3_doses_of_penta_or_hepatiti_pct`), '*'), '[()]', '') AS DOUBLE) AS `child_12_23m_who_have_received_3_doses_of_penta_or_hepatiti_pct`,
  try_cast(regexp_replace(nullif(trim(`child_9_35m_who_received_a_vit_a_in_the_last_6_months_pct`), '*'), '[()]', '') AS DOUBLE) AS `child_9_35m_who_received_a_vit_a_in_the_last_6_months_pct`,
  try_cast(regexp_replace(nullif(trim(`child_12_23m_who_received_most_of_their_vaccinations_in_a_p_pct`), '*'), '[()]', '') AS DOUBLE) AS `child_12_23m_who_received_most_of_their_vaccinations_in_a_p_pct`,
  try_cast(regexp_replace(nullif(trim(`child_12_23m_who_received_most_of_their_vaccinations_in_a_2_pct`), '*'), '[()]', '') AS DOUBLE) AS `child_12_23m_who_received_most_of_their_vaccinations_in_a_2_pct`,
  try_cast(regexp_replace(nullif(trim(`children_with_diarrhoea_2wk_who_received_oral_rehydration_s_pct`), '*'), '[()]', '') AS DOUBLE) AS `children_with_diarrhoea_2wk_who_received_oral_rehydration_s_pct`,
  try_cast(regexp_replace(nullif(trim(`children_with_diarrhoea_2wk_who_received_zinc_child_u5_pct`), '*'), '[()]', '') AS DOUBLE) AS `children_with_diarrhoea_2wk_who_received_zinc_child_u5_pct`,
  try_cast(regexp_replace(nullif(trim(`children_with_diarrhoea_2wk_taken_to_a_health_facility_or_h_pct`), '*'), '[()]', '') AS DOUBLE) AS `children_with_diarrhoea_2wk_taken_to_a_health_facility_or_h_pct`,
  try_cast(regexp_replace(nullif(trim(`children_with_fever_or_symptoms_of_ari_2wk_taken_to_a_healt_pct`), '*'), '[()]', '') AS DOUBLE) AS `children_with_fever_or_symptoms_of_ari_2wk_taken_to_a_healt_pct`,
  try_cast(regexp_replace(nullif(trim(`children_under_age_3_years_breastfed_within_one_hour_of_bir_pct`), '*'), '[()]', '') AS DOUBLE) AS `children_under_age_3_years_breastfed_within_one_hour_of_bir_pct`,
  try_cast(regexp_replace(nullif(trim(`child_u6m_exclusively_breastfed_pct`), '*'), '[()]', '') AS DOUBLE) AS `child_u6m_exclusively_breastfed_pct`,
  try_cast(regexp_replace(nullif(trim(`child_6_8m_receiving_solid_or_semi_solid_food_and_breastmil_pct`), '*'), '[()]', '') AS DOUBLE) AS `child_6_8m_receiving_solid_or_semi_solid_food_and_breastmil_pct`,
  try_cast(regexp_replace(nullif(trim(`breastfeeding_child_6_23m_receiving_an_adequate_diet16_17_pct`), '*'), '[()]', '') AS DOUBLE) AS `breastfeeding_child_6_23m_receiving_an_adequate_diet16_17_pct`,
  try_cast(regexp_replace(nullif(trim(`non_breastfeeding_child_6_23m_receiving_an_adequate_diet16_pct`), '*'), '[()]', '') AS DOUBLE) AS `non_breastfeeding_child_6_23m_receiving_an_adequate_diet16_pct`,
  try_cast(regexp_replace(nullif(trim(`total_child_6_23m_receiving_an_adequate_diet16_17_pct`), '*'), '[()]', '') AS DOUBLE) AS `total_child_6_23m_receiving_an_adequate_diet16_17_pct`,
  try_cast(regexp_replace(nullif(trim(`child_u5_who_are_stunted_height_for_age_18_pct`), '*'), '[()]', '') AS DOUBLE) AS `child_u5_who_are_stunted_height_for_age_18_pct`,
  try_cast(regexp_replace(nullif(trim(`child_u5_who_are_wasted_weight_for_height_18_pct`), '*'), '[()]', '') AS DOUBLE) AS `child_u5_who_are_wasted_weight_for_height_18_pct`,
  try_cast(regexp_replace(nullif(trim(`child_u5_who_are_severe_wasted_weight_for_height_19_pct`), '*'), '[()]', '') AS DOUBLE) AS `child_u5_who_are_severe_wasted_weight_for_height_19_pct`,
  try_cast(regexp_replace(nullif(trim(`child_u5_who_are_underweight_weight_for_age_18_pct`), '*'), '[()]', '') AS DOUBLE) AS `child_u5_who_are_underweight_weight_for_age_18_pct`,
  try_cast(regexp_replace(nullif(trim(`child_u5_who_are_overweight_weight_for_height_20_pct`), '*'), '[()]', '') AS DOUBLE) AS `child_u5_who_are_overweight_weight_for_height_20_pct`,
  try_cast(regexp_replace(nullif(trim(`child_6_59m_who_are_anaemic_lt_11_0_g_dl_22_pct`), '*'), '[()]', '') AS DOUBLE) AS `child_6_59m_who_are_anaemic_lt_11_0_g_dl_22_pct`,
  try_cast(regexp_replace(nullif(trim(`pregnant_w15_49_who_are_anaemic_lt_11_0_g_dl_22_pct`), '*'), '[()]', '') AS DOUBLE) AS `pregnant_w15_49_who_are_anaemic_lt_11_0_g_dl_22_pct`,
  try_cast(regexp_replace(nullif(trim(`all_w15_19_who_are_anaemic_pct`), '*'), '[()]', '') AS DOUBLE) AS `all_w15_19_who_are_anaemic_pct`
FROM mdp.bronze.nfhs5;
